export enum StorageEnum {
  // 全局设置
  TEAM_SYSTEM_SETTING_STORE = 'TEAM_SYSTEM_SETTING',
  // token 等信息
  TEAM_ACCESS_TOKEN_STORE = 'TEAM_ACCESS_TOKEN',
  // 登录信息
  TEAM_LOGIN_INFO_STORE = 'TEAM_LOGIN_INFO',
  // 语言
  TEAM_LANG_STORE = 'TEAM_LANG',
  // 当前选择的主题
  TEAM_DESIGN_STORE = 'TEAM_DESIGN',
  // 工作台布局配置
  TEAM_CHART_LAYOUT_STORE = 'TEAM_CHART_LAYOUT',
  // 工作台需要保存的数据
  TEAM_CHART_STORAGE_LIST = 'TEAM_CHART_STORAGE_LIST',
  // 用户存储的图片媒体
  TEAM_USER_MEDIA_PHOTOS = 'TEAM_USER_MEDIA_PHOTOS'
}
